apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"goldpinger"},"name":"goldpinger","namespace":"default"},"spec":{"ports":[{"name":"http","nodePort":30080,"port":8080,"targetPort":8080}],"selector":{"app":"goldpinger"},"type":"NodePort"}}
  creationTimestamp: "2023-05-21T21:00:22Z"
  labels:
    app: goldpinger
  name: goldpinger-lb
  namespace: default
  resourceVersion: "3143"
  uid: 2c4aab3d-c30f-45ce-b2c3-1d2e83c8dbc0
spec:
  healthCheckNodePort: 31387
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    appProtocol: http
    targetPort: 8080
  selector:
    app: goldpinger
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
