apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: goldpingering-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: goldpinger
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: goldpinger
      ports:
        - protocol: TCP
          port: 8080