apiVersion: v1
kind: Service
metadata:
  name: goldpingerlocallb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: goldpinger
